services:
  sqp_postgres_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=POSTGRES_DB
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
    volumes:
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
