services:
  sqp_postgres_db:
    env_file:
    - path: ./.env
      required: true # default
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}       # Use environment variable reference
      - POSTGRES_USER=${POSTGRES_USER}   # Use environment variable reference
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Use environment variable reference
    volumes:
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
