services:
  sqp_postgres_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=scoredb
      - POSTGRES_PASSWORD=password
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
